# Generated by Django 2.0.6 on 2019-07-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojtapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status_set',
            old_name='status_text',
            new_name='lan',
        ),
    ]
