# Generated by Django 2.0.6 on 2019-07-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojtapp', '0002_auto_20190712_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_set',
            name='switch',
        ),
        migrations.DeleteModel(
            name='status_set',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
