# Generated by Django 2.0.6 on 2019-07-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ojtapp', '0003_auto_20190712_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrl_switch', models.CharField(max_length=2)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='status_set',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojtapp.Switch'),
        ),
    ]
