# Generated by Django 2.2.3 on 2019-07-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ojtapp', '0004_auto_20190712_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lan_ConnectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=10)),
                ('set', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='ctrl_switch',
            new_name='switch_number',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status_set',
        ),
        migrations.AddField(
            model_name='lan_connectiontype',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojtapp.Switch'),
        ),
    ]
