# Generated by Django 2.2.3 on 2019-07-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojtapp', '0005_auto_20190724_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lan_ConnectionType',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
