# Generated by Django 2.2.3 on 2019-07-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojtapp', '0008_auto_20190724_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch_set',
            name='author',
        ),
    ]
