# Generated by Django 2.2.3 on 2019-07-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojtapp', '0009_remove_switch_set_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select',
            name='author',
        ),
        migrations.DeleteModel(
            name='Switch_set',
        ),
        migrations.DeleteModel(
            name='Select',
        ),
    ]
