# Generated by Django 2.2.3 on 2019-07-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ojtapp', '0012_auto_20190724_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=50)),
                ('set', models.IntegerField(default=0)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojtapp.Switch_set')),
            ],
        ),
    ]
