# Generated by Django 2.2.3 on 2019-07-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojtapp', '0013_select_switch_set'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Select',
        ),
        migrations.DeleteModel(
            name='Switch_set',
        ),
    ]
